name: DeathSwap
version: 1.16.1
main: io.github.edwardhuahan.deathswap.DeathSwap

commands:
  startswap:
    description: Begin the game
    usage: /startswap Playername
  stopswap:
    description: Stop the game
    usage: /stopswap